---
title: "HW 1"
author: "Kiera Matiska"
date: "1/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# attach packages
library(tidyverse)
library(here)
library(patchwork)
library(cowplot)
library(lubridate)
library(paletteer)
```

## Read in data

```{r}
amphibians <- read_csv(here("data", "sierra_amphibians.csv")) # read in the csv file
```

## Wrangle Data for first visualization

```{r}
# change survey_date column to a value with only the year
amphibians_date <- amphibians %>% # identify data set
  mutate(survey_date = year(mdy(survey_date))) # column calls only year

# Create data subset
amphibians_subset <- amphibians_date %>% # identify data set
  select(survey_date, amphibian_species, amphibian_life_stage) %>% # Only select certain columns
  filter(amphibian_species == "RAMU", amphibian_life_stage != "EggMass") # filter for species "RAMU" and remove "EggMass" life stage

# create new data set with species name spelled out
amphibians_ramu <- amphibians_subset %>% # identify data set
  mutate(amphibian_species = case_when(
    amphibian_species == "RAMU" ~ "Rana muscosa" # spell out scientific name of species
  ))

# create a summary table to find counts of Rana muscosa by year and life stage
ramu_summary <- amphibians_ramu %>% # create a summary table
  group_by(survey_date, amphibian_life_stage) %>% 
  summarize(count = n()) # count number of individuals by year and life stage
```

### First Data Visualization

```{r}
# create a visualizing plotting year and life stage against number of individuals
p1 <- ggplot(data = ramu_summary, # identify data
       aes(x = survey_date, y = count)) + # set x and y parameters
  geom_col(fill = "darkolivegreen3", color = "darkolivegreen4") + # define a column graph and change plot colors
  facet_wrap(~amphibian_life_stage) + # separate counts graph by life stage
  labs(title = "Mountain Yellow-Legged Frog Counts \nby Year Among Life Stages", # add a title
       x = "Year", # change x-axis label
       y = "Number of Individuals") + # change y-axis label
  theme(plot.title = element_text(hjust = 0.5), # center title text
        plot.background = element_rect(fill = "aliceblue"),
        panel.background = element_rect(fill = "gray95")) # color background of plot
```

## Wrangle Data for Visualization # 2

```{r}
amphibians_subset1 <- amphibians_date %>% 
  select(lake_id, survey_date, amphibian_species, amphibian_life_stage, amphibian_number) %>% 
  filter(amphibian_species == "RAMU",
         amphibian_life_stage %in% c("Adult", "SubAdult")) %>% 
  mutate(lake_id = as.character(lake_id))

ramu_summary1 <- amphibians_subset1 %>% 
  group_by(lake_id) %>% 
  summarize(total_lake_counts = sum(amphibian_number))

amphibian_ramu_lake <- ramu_summary1 %>% 
  arrange(desc(total_lake_counts)) %>% 
  slice(1:5) %>% 
  mutate(lake_id = case_when(
    lake_id == "50183" ~ "Lake 50183",
    lake_id == "10223" ~ "Lake 10223",
    lake_id == "10329" ~ "Lake 10329",
    lake_id == "20196" ~ "Lake 20196",
    lake_id == "10225" ~ "Lake 10225"
  ))

```

### Visualize Data

```{r}
p2 <- ggplot(data = amphibian_ramu_lake, 
       aes(x = reorder(lake_id, -total_lake_counts), y = total_lake_counts)) +
  geom_col(fill = "darkolivegreen3", color = "darkolivegreen4") +
  labs(title = "Top Five Mountain Yellow-Legged \nFrog Counts by Lake ID",
       x = "Lake ID",
       y = "Number of Individuals") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.background = element_rect(fill = "aliceblue"),
        panel.background = element_rect(fill = "gray95"))
```

## Add to visualizations together into a single compound

```{r}
plot_grid(p1,
          p2,
          labels = c("A", "B"))
```

